apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
       tier: backend
  templates:
    metadata:
      labels:
        tier: backend
  spec:
    containers:
      - name: WordPress-DB
        image: mysql8.0
        ports:
          - containerPort: 3306
        envFrom:
          - configMapRef:
              name: mysql-config

