apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP 
  selector:
    tier: backend
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
     tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: wordpress-db
          image: mysql
          ports:
            - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-password
                key: password
          envFrom:
            - configMapRef:
                name: mysql-config
      volumes:
        - name: mysql-persistent-volume
          persistentVolumeClaim:
           claimName: mysql-persistent-claim
