apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-presistent-volume
  labels:
    tier: backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
        storage: 6Gi  
