apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP 
  selector:
    matchLabels:
      tier: backend
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306