apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage
  labels:
    tier: frontend
spec:
  capacity:
    storage: 10Gi
  accessModes:
   - ReadWriteMany
  storageClassName: local-storage
  local:
    path: /var/wordpress 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  labels:
    tier: backend
spec:
  capacity:
    storage: 10Gi
  accessModes:
   - ReadWriteMany
  storageClassName: local-storage
  local:
    path: /var/wordpress
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
