apiVersion: v1
kind: Ingress
metadata:
  labels:
    name: wordpress-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: node1
      http:
        paths: 
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-svc
                port:
                  number: 80
