apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-claim
  labels:
    tier: frontend
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
      
