apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  labels:
    tier: frontend
    app: wordpress
data:
  WORDPRESS_DB_HOST: mysql-svc
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_PASSWORD: password
  WORDPRESS_DB_NAME: wordpress_db
