apiVersion: v1
kind: PersistentvolumeClaim
metadata:
  name: wordpress-presistent-claim
  labels:
    tier: frontend
spec:
  accessMode:
    - ReadWriteMany
  resources:
    request:
      storage: 6Gi
      