apiVersion: apps/v1
kind: Deployment
metadata:
  name: Wordpres-Deployment
spec:
  selector:
    matchLabels:
      tier: frontend
  templates:
    metadata:
      labels:
        tier: frontend
    containers:
      - name: Wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: wordpress-config
              