apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  type: ClusterIP
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    tier: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: wordpress
          image: registry.sohato.com/wordpress
          ports:
          - containerPort: 80
          envFrom:
            - configMapRef:
                name: wordpress-config
      volumes:
      - name: wordpress-persistent-volume
        persistentVolumeClaim:
          claimName: wordpress-persistent-claim
