apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-presistent-claim
  labels:
    tier: frontend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
      
