apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  type: NodePort
  selector:
    matchLabels:
      tier: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001